### ISSUE TITLE
Set up CI + Code Coverage

### ISSUE THREAD

**Issue by petrsvihlik** [Enngage/KenticoCloudDeliveryTypeScriptSDK#12]
I think it would be great if there was an indication of the project being buildable and of the % of code covered by automatic tests.

Would you consider setting up CI (e.g. Travis) + export code coverage (to codeclimate/codecov/coveralls..)

I came across several how-tos for TypeScript (most of them are mentioning istanbul and mocha), so it should be doable.

If you need some inspiration regarding yml files, look at the Kentico repos, e.g.:
- https://github.com/Kentico/delivery-sdk-php
- https://github.com/Kentico/delivery-sdk-net

**Comment by Enngage** [comment]
Thanks for the idea! Seems that the Travis is now working for the Master branch -> https://github.com/Enngage/KenticoCloudDeliveryTypeScriptSDK 

I will take a look at the code coverage options.

**Comment by Enngage** [comment]
done, closing.

**Comment by petrsvihlik** [comment]
awesome!
