### ISSUE TITLE
Make get() return a Promise.

### ISSUE THREAD

**Issue by Viclick** [Enngage/KenticoCloudDeliveryTypeScriptSDK#2]
The `get()` method of the` SingleItemQuery<...>` and `MultipleItemQuery<...>` returns an `Observable<...>`.
I mean, ... how many times is the subscribed callback intended to be called?
I suppose the request is resolved once. That, I think, leaves Promise as a more suitable option especially in the light or the recently introduced async/await which is perfectly backwards compatible with Promises. Because they transpile to Promises basically.

**Comment by Enngage** [comment]
I'm not sure this is something we want to do. `Observables `are generally more powerful than `Promises` as you can easily cancel/retry them and do all kinds of other magic with rxjs. `Observables `can be easily converted to `Promises `with `toPromise` method, but it doesn't work the other way around.

Consider the following:
`
itemAsPromise(): Promise<T>{
     return this.item().toPromise();   
 }

item(): Observable<T> {
     return getObservable();
}
`
Developer could then choose which option suits them more although I'm not aware of anything that `Promises` bring over `Observables`.

**Comment by Viclick** [comment]
They bring the possibility to write asynchronous code in a better looking way with async/await.
I didn't know about the `.toPromise()` trick. This is good enough.

Thanks for getting back to me so quickly.
