### ISSUE TITLE
Add Taxonomy endpoint

### ISSUE THREAD

**Issue by petrsvihlik** [Enngage/KenticoCloudDeliveryTypeScriptSDK#20]
There is a new endpoint for retrieving taxonomy groups:

Docu: https://developer.kenticocloud.com/v1/reference#list-taxonomy-groups

.NET SDK: Kentico/delivery-sdk-net#72

**Comment by Enngage** [comment]
https://github.com/Enngage/KenticoCloudDeliveryTypeScriptSDK/releases/tag/v1.6.0
