### ISSUE TITLE
Feature: Support Node.js 

### ISSUE THREAD

**Issue by edouardr** [Enngage/KenticoCloudDeliveryTypeScriptSDK#22]
# Use case
### Using SDK in a Nodejs/Express application
I am working on a REST API developed with Nodejs and Express. Requirement is to read data from Kentico Cloud, execute some treatment on it and then returned the processed data.

I have setup a simple node server with express to deliver the content. I have set up my models as per the 
KenticoCloudSampleJavascriptApp.

# Error
When executing the following code:

```
var config = new kc.DeliveryClientConfig(projectId, typeResolvers); 
var deliveryClient = new kc.DeliveryClient(config); 

deliveryClient.item('home') 
  .depthParameter(3) 
  .get() 
  .subscribe(response => res.json(response)); 
```

This exception is thrown:

```
Error: XMLHttpRequest is not supported by your browser
    at getXMLHttpRequest (D:\_\sample-tool\node_modules\rxjs\observable\dom\AjaxObs
ervable.js:45:19)
    at Object.createXHR (D:\_\sample-tool\node_modules\rxjs\observable\dom\AjaxObse
rvable.js:93:71)
    at Object.tryCatcher (D:\_\sample-tool\node_modules\rxjs\util\tryCatch.js:6:31)
    at AjaxSubscriber.send (D:\_\sample-tool\node_modules\rxjs\observable\dom\AjaxO
bservable.js:191:50)
    at new AjaxSubscriber (D:\_\sample-tool\node_modules\rxjs\observable\dom\AjaxOb
servable.js:180:14)
    at AjaxObservable._subscribe (D:\_\sample-tool\node_modules\rxjs\observable\dom
\AjaxObservable.js:115:16)
    at AjaxObservable.Observable._trySubscribe (D:\_\sample-tool\node_modules\rxjs\
Observable.js:171:25)
    at AjaxObservable.Observable.subscribe (D:\_\sample-tool\node_modules\rxjs\Obse
rvable.js:159:65)
    at MapOperator.call (D:\_\sample-tool\node_modules\rxjs\operator\map.js:54:23)
    at Observable.subscribe (D:\_\sample-tool\node_modules\rxjs\Observable.js:156:2
2)
```
The dependencies of the SDK require the code to work on a browser. It would be great to have the ability to work on a nodejs app.

# Versions
- node: 8.5.0
- kentico-cloud-delivery-typescript-sdk: 1.6.0
- express: 4.15.4

**Comment by Enngage** [comment]
I've had similar issue in the past, but haven't pursued that in much detail. However, do you think you could try using the approach mentioned [here ](https://github.com/ReactiveX/rxjs/issues/2099 )and see if that will work?

**Comment by edouardr** [comment]
Thanks for your answer.

I did try the solution of your link. For the record, this is what I've done:
- install [xmlhttprequest](https://www.npmjs.com/package/xmlhttprequest) npm package
`npm i xmlhttprequest --save-dev`

- initialize the global property with the XMLHttpRequest from the package
```javascript
import xhr from 'xmlhttprequest';
global.XMLHttpRequest = xhr.XMLHttpRequest;
````

It actually fixes the issue. However, it seems weird to me to have to go through this to use the SDK. What's your opinion into using xmlhttprequest package in the SDK instead of rxjs.AjaxObs to make http request?
I am happy to work on it and propose a PR, if you'd like to go down this path.

**Comment by Enngage** [comment]
Thank you for the info. I agree that it would be nice to have, but as far as I know, rxjs is not supported in node.js environment (and they seem to not plan to). I'm not creating the XMLHttpRequest myself, I'm simply using the `AjaxCreationMethod `from rxjs. There some some libraries/extensions that should allow rxjs to work in node.js, but they are often old libraries that are not even maintained. 

The possible solution could be to use the native [http](https://nodejs.org/api/http.html) api of node.js, convert that to observable and have a property that will specify the context during the delivery client initialization. 

Maybe I'm missing something though :) If you know about library/method/approach that might work for this purpose, can you send me a link?

**Comment by Enngage** [comment]
Seems we could leverage `bindNodeCallback `function in combination with `request` as per [this](http://reactivex.io/rxjs/class/es6/Observable.js~Observable.html#static-method-bindNodeCallback) and [this]https://stackoverflow.com/questions/43911353/how-to-create-an-rxjs-observable-from-a-node-request)

**Comment by Enngage** [comment]
This is currently under development and if I don't stumble upon any major issues, it should work in Node.js environments just like in browsers with the use of native [http ](https://nodejs.org/api/http.html#http_http_get_options_callback) provider

**Comment by Enngage** [comment]
Beta version is now published. It seems to work ok, but we need to keep an eye out for any classes that are not present in node.js out of the box (e.g. I could not use URL class). Any feedback as to how this works is welcomed.

**Comment by edouardr** [comment]
is the beta version available via NPM?
I will try it in one of my sample projects, will let you know how it goes.

**Comment by edouardr** [comment]
@Enngage I generated a package out of master branch with `npm pack` (after building the solution).
I then installed the package in one of my project and added the extra param to client as below:
```Typescript
const config: DeliveryClientConfig = new DeliveryClientConfig(projectId, TypeResolvers);
const client: DeliveryClient = new DeliveryClient(config, true);
```

I then try to run my app where I am doing the following call:
```Typescript
  let response: ItemResponses.DeliveryItemListingResponse<Course> = await client.items<Course>()
    .type(ContentTypes.Course.CODE_NAME)
    .equalsFilter(`elements.${ContentTypes.Course.Fields.CODE}`, req.params.code)
    .containsFilter('system.sitemap_locations', [req.params.inst.toLowerCase()])
    .get()
    .toPromise();
``
`
The url that is generated out of this is: `https://deliver.kenticocloud.com/project_id/items?elements.code=421400&system.sitemap_locations[contains]=unsw&system.type=course`

However, the response that I get out of this call is equivalent to `https://deliver.kenticocloud.com/project_id/items` 

It seems that all url parameters are stripped out. I might have done something wrong when packaging it up.

**Comment by Enngage** [comment]
@edouardr, thanks a lot for trying this out! Turns out you found a bug. Problem was that query params were not contained within the `pathName` and had to be added manually. I published new version which should be fixed. 

Can you try that out and see how that works? Thanks again!

**Comment by edouardr** [comment]
@Enngage I did try the new version and it seems to work as expected in the few tests that I made!

**Comment by Enngage** [comment]
Awesome, thanks for the info. 

Since there were no issues since this was released and tests are working, I'm closing this.

**Comment by Enngage** [comment]
Turns out there were issues if AOT was enabled because the code 'required' some native node.js libraries (i.e. 'https') which were used to execute http requests. These libraries could not be resolved and therefore the build process failed. I had to split the node.js support into a dedicated SDK -> https://www.npmjs.com/package/kentico-cloud-delivery-node-sdk
