### ISSUE TITLE
Taxonomy endpoint does not work for preview

### ISSUE THREAD

**Issue by Simply007** [Enngage/KenticoCloudDeliveryTypeScriptSDK#23]
In issue: https://github.com/Enngage/KenticoCloudDeliveryTypeScriptSDK/issues/20 you have provided a way how to use taxonomy end point https://github.com/Enngage/KenticoCloudDeliveryTypeScriptSDK#working-with-taxonomies

When you configure the client to use the preview, requests does not contains preview API key, so responses returns status code 401.

**Comment by Enngage** [comment]
fixed
