### ISSUE TITLE
Pagination for Taxonomies

### ISSUE THREAD

**Issue by petrsvihlik** [Enngage/KenticoCloudDeliveryTypeScriptSDK#24]
[Listing taxonomy groups](https://developer.kenticocloud.com/reference#list-taxonomy-groups) supports pagination. We need to reflect that in the SDK.

```
{
  "taxonomies": [
    {
      "system": {
        "id": "f30c7f72-e9ab-8832-2a57-62944a038809",
        "name": "Personas",
        "codename": "personas",
        "last_modified": "2016-10-20T13:24:00.3200182Z"
      },
      "terms": [
        {
          "name": "Coffee expert",
          "codename": "coffee_expert",
          "terms": [
            {
              "name": "Barista",
              "codename": "barista",
              "terms": []
            },
            {
              "name": "Cafe owner",
              "codename": "cafe_owner",
              "terms": []
            }
          ]
        },
        {
          "name": "Coffee enthusiast",
          "codename": "coffee_enthusiast",
          "terms": [
            {
              "name": "Coffee lover",
              "codename": "coffee_lover",
              "terms": []
            },
            {
              "name": "Coffee blogger",
              "codename": "coffee_blogger",
              "terms": []
            }
          ]
        }
      ]
    },
    {
      "system": {
        "id": "d351400e-0290-87b2-1413-6c411d8ae5a4",
        "name": "Processing type",
        "codename": "processing_type",
        "last_modified": "2017-09-04T12:50:20.7857817Z"
      },
      "terms": [
        {
          "name": "Wet (Washed)",
          "codename": "wet__washed_",
          "terms": []
        },
        {
          "name": "Dry (Natural)",
          "codename": "dry__natural_",
          "terms": []
        },
        {
          "name": "Semi-dry",
          "codename": "semi_dry",
          "terms": []
        }
      ]
    },
    {
      "system": {
        "id": "79b1c5b6-30bc-d076-a236-d9ec9f1ff01b",
        "name": "Product status",
        "codename": "product_status",
        "last_modified": "2016-09-15T10:53:25.2233101Z"
      },
      "terms": [
        {
          "name": "On sale",
          "codename": "on_sale",
          "terms": []
        },
        {
          "name": "Bestseller",
          "codename": "bestseller",
          "terms": []
        }
      ]
    }
  ],
  "pagination": {
    "skip": 0,
    "limit": 3,
    "count": 3,
    "next_page": ""
  }
}
```

**Comment by ASP1234** [comment]
Hey, I would like to help on this issue. Can you explain it a bit?

**Comment by petrsvihlik** [comment]
There are three main endpoints the SDK talks to:

- content items
- content types
- taxonomy groups

By pagination I mean the following part of the response (see above):

```
 "pagination": {
    "skip": 0,
    "limit": 3,
    "count": 3,
    "next_page": ""
  }
```

The first two endpoints (content items and content types) already have support in the SDK. E.g.: https://github.com/Enngage/KenticoCloudDeliveryTypeScriptSDK/blob/5c07316d22df39e8c8b95d39cd2b14691f1e312c/lib/models/type/responses.ts

We need to replicate the functionality for the taxonomy groups endpoint. It'll by mostly copying&pasting the code and making sure the data is deserialized correctly. You should verify that by a unit test.

I'd start by searching for "pagination" in the repository to see the existing [code](https://github.com/Enngage/KenticoCloudDeliveryTypeScriptSDK/search?utf8=%E2%9C%93&q=pagination&type=).

@Enngage do you have any remarks to add?

**Comment by petrsvihlik** [comment]
@ASP1234 thank you for your interest!
@Enngage can you add Nimish as a collaborator to the project? you'll be able to assign the item to him then.

**Comment by Enngage** [comment]
Hey, 

@petrsvihlik  Explained things very well, so you can try working on it, just let me know in this thread if you do. Make your fork and submit PR please.

**Comment by ASP1234** [comment]
@petrsvihlik Thanks for the explanation. Will send you a PR by tomorrow.

**Comment by Enngage** [comment]
fixed
