### ISSUE TITLE
Feature: Support generic data retrieval without the need of registering types

### ISSUE THREAD

**Issue by Enngage** [Enngage/KenticoCloudDeliveryTypeScriptSDK#25]
As title suggest, we might want to enable querying for items of 'dynamic' types which do not have any class bound to it.

**Comment by daemoon** [comment]
Hey, so if no type was provided then return value should be of type ContentItem? Can then elements value be object?

**Comment by Enngage** [comment]
Hi, yeah, pretty much. Currently all types need to be registered during the initialization of the DeliveryClient which means if a new type was introduced in Kentico Cloud & particular instance of that type is included in the resposne, the SDK will throw an Error because it would not recognize the type. 

I'm planning some larger refactoring so I will probably have to take this one. Did you want to take some issue?

**Comment by daemoon** [comment]
Yeah, I did. But I'm not sure if I'll have time to do this in near future.

**Comment by Enngage** [comment]
Done: https://github.com/Enngage/KenticoCloudDeliveryTypeScriptSDK/releases/tag/v2.2.0
