### ISSUE TITLE
Property decorator - Resolving field

### ISSUE THREAD

**Issue by edouardr** [Enngage/KenticoCloudDeliveryTypeScriptSDK#32]
While working with the SDK, I found tedious to create translators for field names.
I would like to propose the following approach to resolve property names: **Use Typescript Decorators to set the codename at the property level**

### Example:

``` Typescript
export class Article extends ContentItem {
  @codeName('teaser_image')
  public teaserImage: Fields.AssetsField;
  public title: Fields.TextField;
  public summary: Fields.TextField;

  constructor() {
    super()
  }
}
``` 

### Advantages

- SDK being built with Typescript, we can use its Decorator feature
- Easy to read
- no need to create an map object of the code names
- can use constants `@codeName(ContentTypes.Article.fields.teaserImage)`

### Work
I have started working on this [here](https://github.com/edouardr/angular-kentico-headless/blob/develop/src/app/providers/codename-decorator.ts)
It is currently working as is and would require some refactoring - _I don't really like having to path the instance in the decorator._

What I did was to:
- Create a property decorator that defines the code name of KC field
- in the model class inheriting from ContentItem - override propertyResolver method, retrieve a property by decorator.

I believe the last one could be moved to the ContentItem class itself and therefore, we wouldn't to override propertyResolver method anymore.
 
Please, let me know what do you think.

Thanks.

**Comment by Enngage** [comment]
Hi,

This is awesome. I like the use of decorators. In fact, I'm using that in new Java SDK I'm working on. 

Ideally, this mapping should be done in `FieldMapService  `class where current resolving takes place:

```
 properties.forEach(fieldName => {
            var field = item.elements[fieldName] as FieldInterfaces.IField;
            var propertyName;

            // resolve field to a custom model property
            if (itemTyped.propertyResolver) {
                propertyName = itemTyped.propertyResolver(fieldName);
            }

            // resolve field name using decorator here

            // if property name is null/empty, use elements codename
            if (!propertyName) {
                propertyName = fieldName;
            }
            itemTyped[propertyName] = this.mapField(field, modularContent, itemTyped, queryConfig);
        });
```
The `ContentItem ` should be a simple model without any business logic. Also, the current property resolver should not be removed because it might need to be used in JavaScript applications where decorators are not possible as far as I know. 

Do you want to take this feature?

**Comment by edouardr** [comment]
Glad you like it! Agreed with you to leave the property resolver for Javascript users.

Yes happy to take it!

**Comment by Enngage** [comment]
Awesome, thanks! Please go ahead and submit a PR once ready.
