### ISSUE TITLE
No support for resolving links in rich text?

### ISSUE THREAD

**Issue by ChristopherJennings** [Enngage/KenticoCloudDeliveryTypeScriptSDK#4]
Am I missing something, or is there no way to specify how links in rich text fields will be resolved? I imagine it would be very similar to how modular content is resolved, but looking for `a` tags with `data-item-id` attributes and no `href` attribute value.

**Comment by ChristopherJennings** [comment]
I did look into [resolving url slugs globally](https://github.com/Enngage/KenticoCloudDeliveryTypeScriptSDK#resolving-url-slugs-globally), but this doesn't appear to be used for links inline in rich text fields. That seems like it is designed for getting an item   from the API directly and then getting the URL.

**Comment by Enngage** [comment]
You are right, the HTML of rich text is not replaced with actual links from the `Url slug resolver`. This is a good idea to have, I'll definitely look into it once I'm back in Brno.  Thanks!

**Comment by ChristopherJennings** [comment]
I'm not against taking this, but given my current availability I'm not sure when I'd get to it. Maybe we could connect this week to discuss more specifics?

**Comment by Enngage** [comment]
I'm on-site in Greece for the following 2 weeks :-) If you have time, feel free to take this. If not, I'll be happy to take a look once I'm back.

**Comment by Enngage** [comment]
Should be now fixed. Can you try to verify?

**Comment by Enngage** [comment]
Refactored (https://github.com/Enngage/KenticoCloudDeliveryTypeScriptSDK/commit/39e0ee175caa7740db40595901a35ff2d3b49622)
