### ISSUE TITLE
Support handling of transient faults

### ISSUE THREAD

**Issue by JanLenoch** [Enngage/KenticoCloudDeliveryTypeScriptSDK#43]
Add a capability of dealing with transient network outages via the following retry policy:

* Let the client code define a maximum amount of retry attempts, preferably via the DeliveryClientConfig class.
* If not specified in the config, the retry policy should be disabled by default.
* If specified, the Delivery client should retry in exponential retry intervals.
* The interval, in milliseconds, is always calculated as a power of the number 2. The exponent is the ordinal number of the next attempt. The result is then multiplied by 100. The order is one-based. For instance, the first retry attempt interval equals to (2<sup>2</sup> * 100), the second equals to (2<sup>3</sup> * 100), etc.
* When all retry attempts fail, the SDK should notify the client code about it, preferable via an exception.

**Comment by Enngage** [comment]
Released in `v2.5.3`

**Comment by Enngage** [comment]
Retry functionality is now enabled by default and set to 3 attempts.

**Comment by petrsvihlik** [comment]
excellent, thanks @Enngage
