### ISSUE TITLE
Uncaught ReferenceError: exports is not defined

### ISSUE THREAD

**Issue by Tungamirai** [Enngage/KenticoCloudDeliveryTypeScriptSDK#44]
Getting an error Uncaught ReferenceError: exports is not defined

at line

`Object.defineProperty(exports, "__esModule", { value: true });
var kentico_cloud_delivery_typescript_sdk_1 = require("kentico-cloud-delivery-typescript-sdk");`

**Comment by Enngage** [comment]
Hi,

Can you share more details as how you are using the SDK and in what environment? The error you are receiving is often related to using CommonJS while not having it installed. See this [question](https://stackoverflow.com/questions/43042889/typescript-referenceerror-exports-is-not-defined).

**Comment by Tungamirai** [comment]
@Enngage Hi Thanks for the answer , that was the problem i was trying run it straight in the browser :0 ... ended up using webpack  to bundle it first

**Comment by Enngage** [comment]
Awesome, thanks for letting me know :-)
