### ISSUE TITLE
Angular AOT build fails when using the Typescript SDK

### ISSUE THREAD

**Issue by dewang** [Enngage/KenticoCloudDeliveryTypeScriptSDK#45]
We are trying to use the Kentico Typescript SDK in an Angular application.
Angular version: 5.2.0
Typescript version: 2.5.3
Kentico version: 2.3.3

The SDK works fine in local development mode and a normal Angular build. However if you try to run an AOT build it fails with a module reference error. I am not certain but this could be due to how the module is defined.

You can find a reproduction at this repo https://github.com/dewang/kentico-test.git. This is an absolutely basic app created using Angular CLI, with the addition of referencing the Kentico SDK.

Running `ng build --aot` fails with the following error
```
ERROR in ./src/app/app.module.ngfactory.js
Module not found: Error: Can't resolve 'kentico-cloud-delivery-typescript-sdk/definitions/client/delivery-client' in '/home/code/src/kentico-test/src/app'
resolve 'kentico-cloud-delivery-typescript-sdk/definitions/client/delivery-client' in '/home/code/src/kentico-test/src/app'
  Parsed request is a module
  using description file: /home/code/src/kentico-test/package.json (relative path: ./src/app)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: /home/code/src/kentico-test/package.json (relative path: ./src/app)
    resolve as module
      /home/code/src/kentico-test/src/app/node_modules doesn't exist or is not a directory
      /home/code/src/kentico-test/src/node_modules doesn't exist or is not a directory
      /home/code/src/node_modules doesn't exist or is not a directory
      /home/dewang/code/akoni/node_modules doesn't exist or is not a directory
      /home/dewang/code/node_modules doesn't exist or is not a directory
      /home/dewang/node_modules doesn't exist or is not a directory
      /home/node_modules doesn't exist or is not a directory
      /node_modules doesn't exist or is not a directory
      looking for modules in /home/code/src/kentico-test/node_modules
        using description file: /home/code/src/kentico-test/package.json (relative path: ./node_modules)
          Field 'browser' doesn't contain a valid alias configuration
        after using description file: /home/code/src/kentico-test/package.json (relative path: ./node_modules)
          using description file: /home/code/src/kentico-test/node_modules/kentico-cloud-delivery-typescript-sdk/package.json (relative path: ./definitions/client/delivery-client)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              /home/code/src/kentico-test/node_modules/kentico-cloud-delivery-typescript-sdk/definitions/client/delivery-client doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              /home/code/src/kentico-test/node_modules/kentico-cloud-delivery-typescript-sdk/definitions/client/delivery-client.ts doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              /home/code/src/kentico-test/node_modules/kentico-cloud-delivery-typescript-sdk/definitions/client/delivery-client.js doesn't exist
            as directory
              /home/code/src/kentico-test/node_modules/kentico-cloud-delivery-typescript-sdk/definitions/client/delivery-client doesn't exist
```

We get a slightly different error in our actual app which does not use Angular CLI, but uses a custom Webpack 3 build.

```
This dependency was not found:

* kentico-cloud-delivery-typescript-sdk/definitions/client/delivery-client in ./src/app/app.module.ngfactory.js, ./src/app/modules/home/home.component.ngfactory.js and 1 other
```

However the base issue is that it cannot resolve the referenced classes from the module.

**Comment by Enngage** [comment]
Thanks for reporting the issue. I've confirmed this error. 

**Short version:** I've found the root cause and you should be able to use Angular's `aot` in the latest released version `2.5.0`. 

**Long version:** This has been the most unfortunate time to report this issue because there is a bug in latest angular CLI (confirmed just Today a few minutes ago - see [here](https://github.com/angular/angular-cli/issues/9550)) which has made debugging a real pain. Additionally, the **parse5** library which I depend on in this SDK has released a new version fixing some crucial bugs when used in node.js environment, but also introduced some new features which are causing the some 'warnings' when you use it in Angular project.

I've raised an issue with Parse5 and hopefully the warning will not be present in future versions.

**Comment by dewang** [comment]
That's perfect, thanks for the quick turnaround.
I've just upgraded to 2.5.0 and can confirm that this does indeed work.

**Comment by Enngage** [comment]
Awesome, let me know if you stumble on anything else!
