### ISSUE TITLE
Field map service may return outdated content

### ISSUE THREAD

**Issue by Suzii** [Enngage/KenticoCloudDeliveryTypeScriptSDK#46]
Hi, I have this use case in which I believe the `FieldMapService` returns old data. It only happens with modular content and the scenario is as follows:
1. I get an item with modular content via `DeliveryClient.item().get()`.
2. I go to app.kenticocloud.com and update one of item's modular items.
3. I get the same item with modular content again.
4. The raw response (`response.debug.rawResponse.xhr.responseText`) contains fresh data, however the processed item returned from the SDK is of an old version.

IMHO, the problem lies in the fact, that same instance of `DeliveryClient` is used for both requests, which has same instance of `QueryService` and somewhere inside same instance of `FieldMapService` caches/memoizes its processed items without clearing the cache in between consecutive requests. 

To be precise, the item root item is always recomputed aside from [being added to `processedItems`](https://github.com/Enngage/KenticoCloudDeliveryTypeScriptSDK/blob/master/lib/services/field-map.service.ts#L64). However, the modular content [is taken from (possibly outdated) cache](https://github.com/Enngage/KenticoCloudDeliveryTypeScriptSDK/blob/master/lib/services/field-map.service.ts#L213), which results in outdated data being returned.

I am not 100% sure I have investigated this correctly, could you please have a look?

**Comment by Enngage** [comment]
You were absolutely right, thank you for reporting the issue! The `FieldMapService `didn't clear resolved items unless it was reinitialized. This could be an issue especially for SPA. I've released a fix in `2.5.1` version. 

Can you try that and let me know?

**Comment by Suzii** [comment]
Works as intended, thanks for a quick fix! :)
