### ISSUE TITLE
Better naming mapping

### ISSUE THREAD

**Issue by ChristopherJennings** [Enngage/KenticoCloudDeliveryTypeScriptSDK#6]
In trying to use this I got seriously annoyed by having to map all the properties from something like `body_copy` to `bodyCopy` manually for each type. I implemented a helper method to do this, and thought maybe this should be incorporated into the SDK... Thoughts? Here's my implementation: https://gist.github.com/ChristopherJennings/3086c7225f6b391ecca9feb6bf3affc4

**Comment by ChristopherJennings** [comment]
Perhaps we could alternatively or additionally alter the documentation to cover this scenario (https://github.com/Enngage/KenticoCloudDeliveryTypeScriptSDK#property-binding-in-models)

**Comment by ChristopherJennings** [comment]
This is coming from a discussion had on https://github.com/Kentico/cloud-sample-app-js/issues/7

**Comment by Enngage** [comment]
I completely agree that mapping properties can be really tedious which is why I created a sibling project which can generate typescript models from your cloud project. In fact, I implemented the exact same method as you did :-) Check [this ](https://github.com/Enngage/KenticoCloudModelGeneratorUtility/blob/master/lib/ts-generator.js#L118) out. 

To me, it makes more sense to keep this code in generator rather then in the TypeScript SDK as it could make it 'less' transparent. What do you think?

**Comment by ChristopherJennings** [comment]
I guess the code generator is a better place for this to live. This largely came up for me as I discovered the code generator only after I had gone through and built everything out when I was first trying this. Maybe we should promote the code generator more heavily in the documentation of the TS SDK?

**Comment by Enngage** [comment]
Currently, it is included [here ](https://github.com/Enngage/KenticoCloudDeliveryTypeScriptSDK#dont-want-to-waste-time-creating-models-manually) in the documentation. Do you think there is a better place for it or that we should include it right in the first example?

Maybe what we could have is some sort of 'utility' helper class within the SDK for some common functionality and one of it could be this conversion. In the binding callback you would then call this method against the property name. It would make the code less obvious, but it would save a lot of code - especially if you have model with a ton of properties.

**Comment by ChristopherJennings** [comment]
I think mentioning it in both places in the docs where creating models is
mentioned would be good. I'd also move it as a preface to the sections.
Something like, "We recommend using the code generator for your models, but
if you need to customize the models read on for more details."

**Comment by Enngage** [comment]
added comment to readme
